language: java

jdk:
  - oraclejdk8
  
cache:
  directories:
    - '$HOME/.m2/repository'
 
install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  
script:
  - mvn test jacoco:report
  
after_success:
  - mvn coveralls:report